Aim : Write a Prgm to implement k-Nearest Neighbour algorithm to classify the iris data set.

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

The dataset contains the details of users in a social networking site to find whether a user buys a product by clicking the ad on the site based on their salary, age, and gender.

In [ ]:
df = pd.read_csv('Social_Network_Ads.csv')
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [ ]:
X = df.iloc[:, [1, 2, 3]].values
y = df.iloc[:, -1].values
print(X)
print(y)

[['Male' 19 19000]
 ['Male' 35 20000]
 ['Female' 26 43000]
 ...
 ['Female' 50 20000]
 ['Male' 36 33000]
 ['Female' 49 36000]]
[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 1 0 0 0 1 0 0 0 1 0 1
 1 1 0 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0 0 1
 1 0 1 1 0 1 1 0 0 1 0 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 0 1 0 1 1 1 1 0 0 0
 1 1 0 1 1 1 1 1 0 0 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 1 0 1 1 0 0 0 1 1 0 1 0
 0 1 0 1 0 0 1 1 0 0 1 1 0 1 1 0 0 1 0 1 0 1 1 1 0 1 0 1 1 1 0 1 1 1 1 0 1
 1 1 0 1 0 1 0 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,0] = le.fit_transform(X[:,0])

In [ ]:
print(X)

[[1 19 19000]
 [1 35 20000]
 [0 26 43000]
 ...
 [0 50 20000]
 [1 36 33000]
 [0 49 36000]]


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)
print(X_train)
print(X_test)
print(y_train)
print(y_test)

[[1 58 144000]
 [0 59 83000]
 [0 24 55000]
 [0 26 35000]
 [0 58 38000]
 [0 42 80000]
 [0 40 75000]
 [1 59 130000]
 [0 46 41000]
 [0 41 60000]
 [1 42 64000]
 [0 37 146000]
 [0 23 48000]
 [1 25 33000]
 [1 24 84000]
 [0 27 96000]
 [1 23 63000]
 [1 48 33000]
 [1 48 90000]
 [1 42 104000]
 [0 44 39000]
 [1 32 120000]
 [0 38 50000]
 [0 32 135000]
 [0 52 21000]
 [0 53 104000]
 [1 39 42000]
 [1 38 61000]
 [0 36 50000]
 [0 36 63000]
 [0 35 25000]
 [1 35 50000]
 [1 42 73000]
 [0 47 49000]
 [0 59 29000]
 [1 49 65000]
 [0 45 131000]
 [0 31 89000]
 [0 46 82000]
 [0 47 51000]
 [1 26 15000]
 [1 60 102000]
 [0 38 112000]
 [1 40 107000]
 [0 42 53000]
 [1 35 59000]
 [1 48 41000]
 [0 48 134000]
 [0 38 113000]
 [1 29 148000]
 [0 26 15000]
 [1 60 42000]
 [1 24 19000]
 [1 42 149000]
 [0 46 96000]
 [1 28 59000]
 [1 39 96000]
 [1 28 89000]
 [1 41 72000]
 [1 45 26000]
 [0 33 69000]
 [0 20 82000]
 [1 31 74000]
 [1 42 80000]
 [0 35 72000]
 [0 33 149000]
 [1 40 71000]
 [0 51 146000]
 [1 46 79000]
 [1 35 75000]
 [1

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)
print(X_test)

[[ 1.02532046e+00  1.92295008e+00  2.14601566e+00]
 [-9.75304830e-01  2.02016082e+00  3.78719297e-01]
 [-9.75304830e-01 -1.38221530e+00 -4.32498705e-01]
 [-9.75304830e-01 -1.18779381e+00 -1.01194013e+00]
 [-9.75304830e-01  1.92295008e+00 -9.25023920e-01]
 [-9.75304830e-01  3.67578135e-01  2.91803083e-01]
 [-9.75304830e-01  1.73156642e-01  1.46942725e-01]
 [ 1.02532046e+00  2.02016082e+00  1.74040666e+00]
 [-9.75304830e-01  7.56421121e-01 -8.38107706e-01]
 [-9.75304830e-01  2.70367388e-01 -2.87638347e-01]
 [ 1.02532046e+00  3.67578135e-01 -1.71750061e-01]
 [-9.75304830e-01 -1.18475597e-01  2.20395980e+00]
 [-9.75304830e-01 -1.47942605e+00 -6.35303205e-01]
 [ 1.02532046e+00 -1.28500455e+00 -1.06988428e+00]
 [ 1.02532046e+00 -1.38221530e+00  4.07691369e-01]
 [-9.75304830e-01 -1.09058306e+00  7.55356227e-01]
 [ 1.02532046e+00 -1.47942605e+00 -2.00722133e-01]
 [ 1.02532046e+00  9.50842613e-01 -1.06988428e+00]
 [ 1.02532046e+00  9.50842613e-01  5.81523798e-01]
 [ 1.02532046e+00  3.67578135e-

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

We are using 3 parameters in the model creation. n_neighbors is setting as 5, which means 5 neighborhood points are required for classifying a given point. The distance metric we are using is Minkowski, the equation for it is given below
# formula
As per the equation, we have to select the p-value also. p = 1, Manhattan Distance p = 2, Euclidean Distance p = infinity, Cheybchev Distance in our problem, we are choosing the p as 2(also u can choose the metric as "euclidean")

In [ ]:
y_pred = classifier.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1])

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test, y_pred)
ac = accuracy_score(y_test,y_pred)
print(cm)
print(ac)

[[55  3]
 [ 1 21]]
0.95
