In [ ]:
import numpy as np
m=np.array([[1,2],[8,9]])
print(m)
w,v=np.linalg.eigvals(m)

[[1 2]
 [8 9]]


In [ ]:
print("eigen values:",w)
print("eigen vectors;",v)

eigen values: -0.6568542494923797
eigen vectors; 10.65685424949238


In [ ]:
import numpy as np
import pandas as pd
df = pd.read_csv("/content/iris.csv")
df.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [ ]:
from sklearn.preprocessing import StandardScaler
features=['sepal.length','sepal.width','petal.length','petal.width']

In [ ]:
X=df.loc[:,features].values
Y=df.loc[:,['variety']]

In [ ]:
X_scaled=StandardScaler().fit_transform(X)
X_scaled[:5]

array([[-0.90068117,  1.01900435, -1.34022653, -1.3154443 ],
       [-1.14301691, -0.13197948, -1.34022653, -1.3154443 ],
       [-1.38535265,  0.32841405, -1.39706395, -1.3154443 ],
       [-1.50652052,  0.09821729, -1.2833891 , -1.3154443 ],
       [-1.02184904,  1.24920112, -1.34022653, -1.3154443 ]])

In [ ]:
features1=X_scaled.T
cov_matrix=np.cov(features1)
cov_matrix[:5]

array([[ 1.00671141, -0.11835884,  0.87760447,  0.82343066],
       [-0.11835884,  1.00671141, -0.43131554, -0.36858315],
       [ 0.87760447, -0.43131554,  1.00671141,  0.96932762],
       [ 0.82343066, -0.36858315,  0.96932762,  1.00671141]])

In [ ]:
values,vectors=np.linalg.eig(cov_matrix)

In [ ]:
print("eigen values:",values)
print("eigen vectors:",vectors)

eigen values: [2.93808505 0.9201649  0.14774182 0.02085386]
eigen vectors: [[ 0.52106591 -0.37741762 -0.71956635  0.26128628]
 [-0.26934744 -0.92329566  0.24438178 -0.12350962]
 [ 0.5804131  -0.02449161  0.14212637 -0.80144925]
 [ 0.56485654 -0.06694199  0.63427274  0.52359713]]


In [ ]:
explained_variances=[]
for i in range(len(values)):
  explained_variances.append(values[i]/np.sum(values))
print(np.sum(explained_variances),explained_variances)

0.9999999999999999 [0.729624454132999, 0.22850761786701723, 0.03668921889282867, 0.005178709107155017]
